/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aws.sm.migrator;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.util.List;
import java.util.Optional;
import java.util.concurrent.Callable;

@Command(name = "AWSSMMigrator", mixinStandardHelpOptions = true, version = "1.0",
        description = "Migrates AWS Secret values to line-terminated multi-values."
)
public class AwsSMMigrator implements Callable<Integer> {

    @Option(names = {"-s","--source-prefix"}, paramLabel = "source-prefix/",
            description = "Source Secret Name Prefix which contains the secrets.", required = true)
    private String sourceSecretNamePrefix;
    @Option(names = {"-t","--target-prefix"}, paramLabel = "target-prefix/",
            description = "Target Secret Name Prefix where to create the secrets.", required = true)
    private String targetSercretNamePrefix;
    @Option(names = {"-d", "--dry-run"}, description = "Dry run only.")
    private boolean dryRun = false;


    @Override
    public Integer call() {
        try(final AwsSecretsManager awsSecretsManager = new AwsSecretsManager(dryRun)) {
            final List<String> secretsList = awsSecretsManager.getAllSecretsForPrefix(sourceSecretNamePrefix);
            awsSecretsManager.transformSecrets(targetSercretNamePrefix, secretsList);
        } catch (Exception e) {
            System.err.println("Error encountered: " + e.getMessage());
            e.printStackTrace();
            return -1;
        }
        return 0;
    }



    public static void main(String[] args) {
        int exitCode = new CommandLine(new AwsSMMigrator()).execute(args);
        System.exit(exitCode);
    }
}
